version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
    versioning-strategy: increase
    open-pull-requests-limit: 10
    exclude-paths:
      - test/fixtures/astro-5
      - test/fixtures/astro-6
    ignore:
      - dependency-name: '@types/node'
        update-types: [version-update:semver-major]
    groups:
      astro:
        patterns:
          - astro
          - '@astrojs/*'
      takumi:
        patterns:
          - takumi
          - '@takumi-rs/*'
      dev-dependencies:
        dependency-type: development
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 10
